### ISSUE TITLE
[Lab5] Зачем посылать потверждение микропроцессору клавиатуры

### ISSUE THREAD

**Issue by Anakael** [JAkutenshi/spbetu_os_2020_8382#94]
Код из методички:
```
in al, 61h
mov ah, al
or al, 80h
out 61h, al
xchg ah, al
out 61h, al
```

Вопрос: Что именно выполняет этот код? Видимых изменений без него нет.

Более того, дальше идёт уточнее про 6ой бит.
![image](https://user-images.githubusercontent.com/17771546/82608588-aeb13b00-9bc3-11ea-9bad-49aff0e2c119.png)
```
in al, 61h
mov ah, al
and al, 0bfh
out 61h, al
xchg ah, al
out 61h, al
```
То есть такой код должен отключать клавиатуру, верно? Но при запуске этого не происходит.
Вопрос: почему?

Я предполагаю, что дело в том, что dos запускается в эмуляторе и хостовая ОС сама высталяет нужные флаге в контроллере. Это так?

Такой же вопрос от очистку буфера клавиатуры - без неё тоже всё работет.

**Comment by JAkutenshi** [comment]
>То есть такой код должен отключать клавиатуру, верно? Но при запуске этого не происходит.

Очень странно. У меня клавиатура отключается и в симуляторе, и в виртуалке. Если вот этот вот код 
```
in al, 61h
mov ah, al
and al, 0bfh
out 61h, al
xchg ah, al
out 61h, al
```

Оставить в теле обработчика, то после загрузки клавиатура выключена.

Насчет первого вопроса я, если честно, не уверен. Если я правильно понимаю, то это некоторый протокол подтверждения МК клавиатуры. У меня есть подозрение, что для того, чтобы это действительно имело вес, надо эмулировать железо с конкретой периферией. По-крайней мере у меня действительно колебания 7го бита эффекта никакого не имеют, проверял в виртуальной машине с досом. Постараюсь не забыть об этом спросить при случае у Александра Федоровича.

**Comment by JAkutenshi** [comment]
Спросил: да, вряд ли в виртуальных машинах или эмуляторе доса это можно ощутить. Мое предположение, что можно сэмулировать железо, но я не готов сейчас все это проверять ибо много иной работы.
